name: CD using Github Actions
# on: push
# jobs:
#     prod-build:
#         runs-on: ubuntu-latest
#         steps:
#             - uses: actions/checkout@v3

#             - name: Build prod site and move contents from dist to root
#               run: |
#                   rm -rf index.html *.webp *.css *.js
#                   cd source/
#                   npm i
#                   npm run build
#                   sudo mv dist/* ../
#                   rm -rf dist node_modules

#             - name: Commit files
#               run: |
#                   git config --local user.email "action@github.com"
#                   git config --local user.name "GitHub Action"
#                   git add .
#                   git commit -m "Added prod build by Hetarth Shah using Github Actions"
#                   git push
